import pygame

# --- USTAWIENIA EKRANU I GRY ---
SCREEN_WIDTH = 900
SCREEN_HEIGHT = 600
FPS = 60

# --- KOLORY ---
WHITE = (255, 255, 255)
BLACK = (0, 0, 0)
RED = (255, 0, 0)
GREEN = (0, 255, 0)
BLUE = (0, 0, 255)
YELLOW = (255, 255, 0)
PINK = (255, 192, 203)
GRAY = (100, 100, 100)
GREEN_BLUE = (50, 166, 154)
LIGHT_GRAY = (200, 200, 200)
LINE_COLORS = [RED, GREEN, BLUE, YELLOW, PINK, GREEN_BLUE]

# --- USTAWIENIA STACJI ---
STATION_RADIUS = 9
STATION_BORDER_THICKNESS = 3
STATION_CAPACITY = 8
STATION_MIN_DISTANCE = 80
STATION_SHAPES = ['circle', 'square', 'triangle', 'star', 'rombus']
MAX_STATIONS = 40
STATIONS_TO_SPAWN_PER_WEEK = 4

# --- USTAWIENIA PASAŻERÓW ---
BASE_PASSENGER_SPAWN_RATE = 100

SCORE_DIVISOR_FOR_REDUCTION = 1

MIN_PASSENGER_SPAWN_RATE = 10

PASSENGER_ICON_SIZE = 10
PASSENGER_ICON_SPACING = 5

# --- USTAWIENIA POCIĄGÓW ---
TRAIN_SPEED = 1.2
TRAIN_CAPACITY = 6
TRAIN_SIZE = 10
MAX_TRAINS = 10

# --- USTAWIENIA CZASU I UI ---
WEEK_DURATION_SECONDS = 60
WEEK_DURATION_FRAMES = FPS * WEEK_DURATION_SECONDS
TRAIN_BUTTON_RECT = pygame.Rect(SCREEN_WIDTH - 120, 70, 100, 40)
WEEK_BAR_RECT = pygame.Rect(20, 60, 150, 15)
WEEK_BAR_COLOR = YELLOW
WEEK_BAR_BG_COLOR = GRAY

# Czasy pojawiania się stacji w trakcie tygodnia (w klatkach)
STATION_SPAWN_TIMES = [((WEEK_DURATION_FRAMES // STATIONS_TO_SPAWN_PER_WEEK) - 1) * i for i in range(1, STATIONS_TO_SPAWN_PER_WEEK + 1)]